dist: focal
language: php
php:
- '8.0'
- 'nightly'
env:
  global:
    - XDEBUG_MODE=coverage
matrix:
  allow_failures:
  - php: nightly
  fast_finish: true
services:
- redis
- memcached
before_install:
- printf "\n" | pecl install memcached
- pecl install uopz 
install:
- composer update
script:
- ./vendor/bin/phpunit --coverage-clover=coverage.clover
after_success:
- if [ "$TRAVIS_PHP_VERSION" == "8.0" ]; then composer global require scrutinizer/ocular; fi
- if [ "$TRAVIS_PHP_VERSION" == "8.0" ]; then composer global exec -v -- "ocular code-coverage:upload --format=php-clover coverage.clover"; fi
