dist: focal
language: php
php:
- '8.0'
- 'nightly'
matrix:
  allow_failures:
  - php: nightly
  fast_finish: true
services:
- redis
- memcached
before_install:
  - pecl install uopz 
install:
- composer update
script:
  ./vendor/bin/phpunit --coverage-clover=coverage.clover
after_script:
- if [ "$TRAVIS_PHP_VERSION" == "8.0" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
- if [ "$TRAVIS_PHP_VERSION" == "8.0" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
